import Link from "next/link";
import { pageUser } from "@/server/page-user";
import { ledgerOptions } from "@/server/ledger";
import { reviewView } from "@/server/review";
import { monthValue } from "@/lib/ledger-validation";
import { formatMoney } from "@/lib/finance";
import { monthLabel } from "@/lib/budget";
import { MonthToolbar } from "@/components/month-toolbar";
const money = (value: string | null) => value === null ? "—" : formatMoney(BigInt(value));
export default async function ReviewPage({ searchParams }: { searchParams: Promise<{ month?: string }> }) {
  const user = await pageUser(), options = await ledgerOptions(user.id), params = await searchParams;
  const parsed = monthValue.safeParse(params.month || options.today.slice(0, 7)), month = parsed.success ? parsed.data : options.today.slice(0, 7), view = await reviewView(user.id, month);
  const retirement = BigInt(view.retirement.employee) + BigInt(view.retirement.match) + BigInt(view.retirement.other);
  const cards = [["Income received", money(view.income)], ["Budgeted spending", money(view.planned)], ["Actual spending", money(view.expenses)], ["Cash savings", money(view.savings)], ["Retirement contributions", formatMoney(retirement)], [view.underBudget !== null && BigInt(view.underBudget) < 0n ? "Over budget by" : "Under budget by", view.underBudget === null ? "—" : formatMoney(BigInt(view.underBudget) < 0n ? -BigInt(view.underBudget) : BigInt(view.underBudget))], ["Savings rate", view.rate === null ? "—" : `${Number(view.rate) / 100}%`], ["Net cash flow", money(view.remaining)]];
  return <main className="page"><div className="page-heading"><div><span className="eyebrow">REFLECT & PLAN AHEAD</span><h1>Monthly review</h1><p className="muted">A factual look at {monthLabel(month)}.</p></div><Link className="button secondary" href={`/calendar?month=${month}`}>View calendar</Link></div><MonthToolbar month={month} path="/review"/>
    <div className="calendar-explainer panel"><strong>{view.status === "complete" ? "Completed calendar month" : view.status === "in-progress" ? "Month in progress · totals are partial" : "Future month · plans only until actuals are recorded"}</strong><p className="muted">This review is generated automatically from saved records when opened. Corrections to the ledger update past reviews; it is not a frozen statement. Scheduled entries are excluded. A dash means no budget or no income for the rate.</p></div>
    <div className="summary-grid">{cards.map(([label, value]) => <section className="summary-card" key={label}><span>{label}</span><strong>{value}</strong><small>{label === "Retirement contributions" ? "Separate from spendable cash" : label === "Savings rate" ? "Cash savings ÷ net income" : "Recorded / saved for this month"}</small></section>)}</div>
    <div className="review-grid"><section className="panel review-panel"><h2>What stands out</h2>{view.categories.some(c => BigInt(c.actual) > 0n) ? <p className="review-highlight">Largest spending category: <strong>{view.categories[0].name}</strong> · {money(view.categories[0].actual)}</p> : <p className="muted">No expenses recorded this month.</p>}<ul className="review-insights">{view.categories.filter(c => c.remaining !== null || (c.change !== null && c.change !== "0")).slice(0, 8).map(c => <li key={c.id}><strong>{c.name}</strong>{c.remaining !== null && <p>{BigInt(c.remaining) < 0n ? `${formatMoney(-BigInt(c.remaining))} over the saved allocation.` : `${money(c.remaining)} remaining in the saved allocation.`}</p>}{c.change !== null && <p>{c.change === "0" ? "Spending was unchanged" : `${formatMoney(BigInt(c.change) < 0n ? -BigInt(c.change) : BigInt(c.change))} ${BigInt(c.change) < 0n ? "less" : "more"} recorded spending`} compared with {view.previous}.</p>}</li>)}</ul><p className="muted">Comparisons use recorded expenses only; an empty prior month is not evidence of zero real-world spending.</p></section>
    <section className="panel review-panel"><h2>Retirement, kept separate</h2><dl className="review-breakdown"><dt>Employee contributions</dt><dd>{money(view.retirement.employee)}</dd><dt>Employer match</dt><dd>{money(view.retirement.match)}</dd><dt>Other employer contributions</dt><dd>{money(view.retirement.other)}</dd></dl><p className="muted">Actual contribution records only. No employer contribution is assumed, and these amounts are excluded from cash savings and net cash flow.</p><h2 className="review-goal-heading">Goal progress through month-end</h2><p className="muted">Reconstructed using current opening allocations and targets plus linked transfers dated through this month. Goals without dated opening allocations are not historical account statements.</p>{view.goals.map(g => <div className="review-goal" key={g.id}><Link className="text-link" href="/goals">{g.name}</Link><strong>{money(g.current)}{g.target ? ` / ${money(g.target)}` : " · No target"}</strong></div>)}{!view.goals.length && <p className="muted">No savings goals yet.</p>}</section></div>
    <section className="panel review-panel"><h2>Category review</h2><div className="chart-table-scroll" tabIndex={0}><table><thead><tr><th scope="col">Category</th><th scope="col">Budgeted</th><th scope="col">Actual</th><th scope="col">Previous month</th><th scope="col">Change</th></tr></thead><tbody>{view.categories.map(c => <tr key={c.id}><th scope="row">{c.name}</th><td>{money(c.planned)}</td><td>{money(c.actual)}</td><td>{money(c.previous)}</td><td>{money(c.change)}</td></tr>)}</tbody></table></div>{!view.categories.length && <p className="muted">No category activity or allocations to compare.</p>}<Link className="text-link" href={`/budget?month=${month}`}>Open this month’s budget →</Link></section>
  </main>;
}
