import Link from "next/link";
import { FinancialPreferences } from "@/components/financial-preferences";
import { ExportPanel } from "@/components/export-panel";
import { pageUser } from "@/server/page-user";
import { withOwner } from "@/server/db";
import { ProfileForm, PreferencesForm, PasswordForm } from "@/components/settings-forms";
export default async function Settings() {
  const user = await pageUser();
  const settings = await withOwner(user.id, tx => tx.userSettings.findUniqueOrThrow({ where: { userId: user.id } }));
  return <main className="page settings-page"><div className="page-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h1>Settings</h1><p className="muted">A few details that make this space your own.</p></div></div><section className="panel settings-panel"><div className="section-heading"><span className="section-number">01</span><div><h2>Your profile</h2><p className="muted">The person behind the plan.</p></div></div><ProfileForm name={user.name} email={user.email}/></section><section className="panel settings-panel"><div className="section-heading"><span className="section-number">02</span><div><h2>Your preferences</h2><p className="muted">Settle into a view that works for you.</p></div></div><PreferencesForm id={settings.id} theme={settings.theme} timezone={settings.timezone}/></section><section className="panel settings-panel" id="security"><div className="section-heading"><span className="section-number">03</span><div><h2>Account security</h2><p className="muted">Keep access to your workspace in your hands.</p></div></div><PasswordForm/></section><section className="panel settings-panel"><div className="section-heading"><div><h2>Financial defaults & reminders</h2><p className="muted">A starting point for new monthly budgets.</p></div></div><FinancialPreferences revision={settings.updatedAt.toISOString()} income={settings.defaultIncomeMinor.toString()} savings={settings.defaultBudgetSavingsMinor.toString()} notifications={settings.notificationsEnabled}/></section><section className="panel settings-panel"><div className="section-heading"><div><h2>Data export</h2><p className="muted">Download your own records.</p></div></div><ExportPanel/></section><section className="panel settings-links"><Link className="text-link" href="/retirement">Retirement settings →</Link><Link className="text-link" href="/onboarding">Revisit setup →</Link></section></main>;
}
