"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { retirementSettingsInput, contributionUpdate, type ContributionView, type RetirementSettingsView } from "@/lib/retirement";
import { retirementInput } from "@/lib/income";
import { parseMoney, formatMoney } from "@/lib/finance";
import { Modal, ErrorMessage, SaveButton } from "./ledger-ui";
async function request(path: string, method: string, data: unknown) { const response = await fetch(`/api/retirement${path}`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not save retirement details."); return result; }
export function RetirementSettingsForm({ settings }: { settings: RetirementSettingsView | null }) {
  const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState(""), [saved, setSaved] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setSaved(false); const parsed = retirementSettingsInput.safeParse({ ...Object.fromEntries(new FormData(event.currentTarget)), expectedRevision: settings?.revision ?? null }); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setBusy(true); try { await request("", "PUT", parsed.data); setSaved(true); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save settings."); } finally { setBusy(false); } }
  return <form className="settings-form" onSubmit={submit}><div className="field-grid">{([{ key: "annualSalary", label: "Annual gross salary", hint: "Independent retirement planning assumption." }, { key: "employeePercent", label: "Employee contribution %", hint: "Percentage of gross salary." }, { key: "matchPercent", label: "Employer match % of salary", hint: "Enter your effective salary percentage; this does not model complex matching rules." }, { key: "otherPercent", label: "Other employer contribution %", hint: "Zero unless you explicitly enter a contribution." }, { key: "currentBalance", label: "Reported current retirement balance", hint: "A manual balance snapshot, independent of contributions. Update it from your statement." }] as const).map(f => <label key={f.key}>{f.label}<input name={f.key} inputMode="decimal" defaultValue={settings?.[f.key] ?? "0"} required/><small className="field-hint">{f.hint}</small></label>)}</div><p className="field-hint">Saving assumptions does not create actual contributions, adjust cash balances, or move money.</p><ErrorMessage message={error}/>{saved && <p role="status" className="notice success">Retirement assumptions saved.</p>}<div className="form-actions"><SaveButton busy={busy}/></div></form>;
}
function ContributionEditor({ entry, today, close }: { entry: ContributionView | null; today: string; close: () => void }) {
  const router = useRouter(), [busy, setBusy] = useState(false), [error, setError] = useState(""), [requestId] = useState(() => crypto.randomUUID());
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const input = { ...Object.fromEntries(new FormData(event.currentTarget)), ...(entry ? { expectedRevision: entry.revision } : { requestId }) }; const parsed = (entry ? contributionUpdate : retirementInput).safeParse(input); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setBusy(true); try { await request(`/contributions${entry ? `/${entry.id}` : ""}`, entry ? "PUT" : "POST", parsed.data); router.refresh(); close(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save contribution."); setBusy(false); } }
  return <Modal title={entry ? "Edit contribution" : "Record actual contribution"} close={close} busy={busy}><form className="dialog-body" onSubmit={submit}><label>Contribution date<input name="date" type="date" min="1900-01-01" max={today} defaultValue={entry?.date ?? today} required/></label><div className="field-grid">{([{ key: "employee", label: "Employee amount" }, { key: "employerMatch", label: "Employer match amount" }, { key: "employerOther", label: "Other employer amount" }] as const).map(f => <label key={f.key}>{f.label}<input name={f.key} inputMode="decimal" defaultValue={entry?.[f.key] ?? "0"} required/></label>)}</div><label>Notes<input name="notes" maxLength={500} defaultValue={entry?.notes ?? ""}/></label><p className="field-hint">Actual amounts only. This updates retirement totals without changing cash accounts or the manually reported retirement balance.</p><ErrorMessage message={error}/><div className="dialog-actions"><SaveButton busy={busy}/></div></form></Modal>;
}
export function RetirementEntries({ records, today }: { records: ContributionView[]; today: string }) {
  const router = useRouter(), [editor, setEditor] = useState<ContributionView | null | undefined>(), [deleting, setDeleting] = useState<ContributionView>(), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function remove() { if (!deleting) return; setBusy(true); setError(""); try { await request(`/contributions/${deleting.id}`, "DELETE", { expectedRevision: deleting.revision }); setDeleting(undefined); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not delete contribution."); } finally { setBusy(false); } }
  return <section className="panel retirement-records"><div className="activity-heading"><h2>Actual contributions</h2><button type="button" className="button primary" onClick={() => setEditor(null)}>Record contribution</button></div>{!records.length && <p className="muted">No contributions recorded for this month. Add actual amounts from your retirement statement.</p>}{records.map(r => <article className="retirement-entry" key={r.id}><div><strong>{r.date}</strong><p>Employee {formatMoney(parseMoney(r.employee))} · Match {formatMoney(parseMoney(r.employerMatch))} · Other {formatMoney(parseMoney(r.employerOther))}</p>{r.notes && <p className="muted">{r.notes}</p>}</div><div className="record-actions"><button type="button" onClick={() => setEditor(r)} aria-label={`Edit contribution on ${r.date}`}>Edit</button><button type="button" onClick={() => { setError(""); setDeleting(r); }} aria-label={`Delete contribution on ${r.date}`}>Delete</button></div></article>)}{editor !== undefined && <ContributionEditor entry={editor} today={today} close={() => setEditor(undefined)}/>} {deleting && <Modal title="Delete contribution?" close={() => setDeleting(undefined)} busy={busy}><div className="dialog-body"><p>The contribution on {deleting.date} will be permanently deleted. Retirement totals and monthly reviews will recalculate.</p><ErrorMessage message={error}/><div className="dialog-actions"><button className="button secondary" disabled={busy} onClick={() => setDeleting(undefined)}>Keep it</button><button className="button danger" disabled={busy} onClick={remove}>{busy ? "Deleting…" : "Delete permanently"}</button></div></div></Modal>}</section>;
}
